### ISSUE TITLE
HTTP 400 error with ACI 1.2h

### ISSUE THREAD

**Issue by Krago27** [brightpuddle/aci-vetr-collector#4]
I got HTTP 400 while using vetr collector with APIC 1.2h.
Is the new version support old ACI like 1.2h?

**Comment by jhafirewall** [comment]
Even i got the HTTP error for ACI code 3.x
-----------------------------------------------
sageCap10:16AM ERR cannot fetch data from the API error="failed to make request: received HTTP status 400"
Press enter to exit.
-------------------------------------------------

how can we fix this??

**Comment by brightpuddle** [comment]
400 errors are due to missing API calls. Fixed in a36d598b0421ace11b995e5b2d4232ed90c85fdc and released in 1.1.2.
